feat: Add components
htmlacademy-react/230508-what-to-watch-9 pull request #4
Opened 2022-02-14 18:07 UTC by BalanarUnity1337

2022-02-14 22:10 UTC, dianatsevan requested changes

2022-02-14 22:10 UTC, dianatsevan commented on project/src/components/player/player.tsx
> +          <button className="player__play" type="button">
Есть компонент `Button`, который также может быть использован здесь и далее либо стоит подумать, действительно ли нам необходим этот компонент?

2022-02-14 22:10 UTC, dianatsevan commented on project/src/components/film-card/film-card.tsx
> +    <article className="small-film-card  catalog__films-card">
Два пробела

2022-02-14 22:10 UTC, dianatsevan commented on project/src/components/icons/icon-add/icon-add.tsx
> +function IconAdd(): JSX.Element {
Так как иконки и так находятся в папке `icons`, то можно отзаться от слова `Icon` в названии компонента (опционально), елси считаешь, что стоит оставить, то нужно поменять порядок слов в названии компонента на `AddIcon` и так далее во всех остальных компонентах иконок

2022-02-14 22:10 UTC, dianatsevan commented on project/src/components/icons/icon-play-s/icon-play-s.tsx
> +function IconPlayS(): JSX.Element {
Не совсем поняла название: что значит `S` в названии компонента?

2022-02-14 22:10 UTC, dianatsevan commented on project/src/components/sign-in/sign-in.tsx
> +        <h1 className="page-title  user-page__title">Sign in</h1>
Два пробела

2022-02-14 22:10 UTC, dianatsevan commented on project/src/components/sign-in/sign-in.tsx
> +      <Header classes={['user-page__head']}>
Классы и далее по файлу

2022-02-14 22:10 UTC, dianatsevan commented on project/src/components/sign-in-field/sign-in-field.tsx
> +      <label className="sign-in__label  visually-hidden" htmlFor={id}>{label}</label>
Два пробела

2022-02-17 16:31 UTC, BalanarUnity1337 commented on project/src/utils/mergeClasses.ts
> +const mergeClasses = (classes: string[] | undefined, staticClass?: string): string => {
Поправил

2022-02-17 16:31 UTC, BalanarUnity1337 commented on project/src/utils/mergeClasses.ts
> +  return Array.isArray(classes)
Поправил

2022-02-17 16:31 UTC, BalanarUnity1337 commented on project/src/components/add-review-page/add-review-page.tsx
> +    <section className="film-card  film-card--full">
Поправил

2022-02-17 16:31 UTC, BalanarUnity1337 commented on project/src/components/add-review-page/add-review-page.tsx
> +        <div className="film-card__poster  film-card__poster--small">
Поправил

2022-02-17 16:31 UTC, BalanarUnity1337 commented on project/src/components/header/header.tsx
> +    <header className={innerClassName}>
Поправил

2022-02-17 16:36 UTC, BalanarUnity1337 commented on project/src/components/header/header.tsx
> +  const isLoggedIn = true; // Будем брать из стора
Принял. Комментарий убрал за ненадобностью.

2022-02-17 16:37 UTC, BalanarUnity1337 commented on project/src/components/logo/logo.tsx
> +type LogoProps = {
Решили оставить `Component` + `Props`

2022-02-17 16:37 UTC, BalanarUnity1337 commented on project/src/components/header-user-block/header-user-block.tsx
> +  const isLoggedIn = true; // Будем брать из стора
Убрал

2022-02-17 16:39 UTC, BalanarUnity1337 commented on project/src/components/app/app.tsx
> +function App({title, genre, year}: AppProps): JSX.Element {
Теперь прокидывается объект в кач-ве пропа

2022-02-17 16:40 UTC, BalanarUnity1337 commented on project/src/components/movie-page/movie-page.tsx
> +        <section className="catalog  catalog--like-this">
Поправил

2022-02-17 16:40 UTC, BalanarUnity1337 commented on project/src/components/movie-page/movie-page.tsx
> +        <Header classes={['film-card__head']} />
Поправил

2022-02-17 16:41 UTC, BalanarUnity1337 commented on project/src/components/film-card-full/film-card-full.tsx
> +type FilmCardFullProps = PropsWithChildren<{
Решили оставить `Component` + `Props`

2022-02-17 16:41 UTC, BalanarUnity1337 commented on project/src/components/film-card-full/film-card-full.tsx
> +    overview: FilmCardOverview(),
Поправил

2022-02-17 16:41 UTC, BalanarUnity1337 commented on project/src/components/film-card-reviews/film-card-reviews.tsx
> +    <div className="film-card__reviews  film-card__row">
Fix

2022-02-17 16:42 UTC, BalanarUnity1337 commented on project/src/components/catalog-films/catalog-films.tsx
> +function CatalogFilms({films}: CatalogFilmsProps): JSX.Element {
Поправил

2022-02-17 16:42 UTC, BalanarUnity1337 commented on project/src/components/catalog-films/catalog-films.tsx
> +    .map((item) => <FilmCard key={item} />);
Изменил передаваемые данные

2022-02-17 16:45 UTC, BalanarUnity1337 commented on project/src/components/main/main.tsx
> +      <FilmCardPromo title={title} genre={genre} year={year}>
Пока обошелся прокидыванием объекта. О применении react context еще подумаю

2022-02-17 16:45 UTC, BalanarUnity1337 commented on project/src/components/main/main.tsx
> +        <Header classes={['film-card__head']} />
Поправил

2022-02-17 16:45 UTC, BalanarUnity1337 commented on project/src/components/main/main.tsx
> +          <h2 className="catalog__title  visually-hidden">Catalog</h2>
Поправил

2022-02-17 16:46 UTC, BalanarUnity1337 commented on project/src/components/film-card-description/film-card-description.tsx
> +        <Button icon={IconPlayS()} classes={['btn--play', 'film-card__button']}>
Изменил

2022-02-17 16:46 UTC, BalanarUnity1337 commented on project/src/components/button/button.tsx
> +function Button({icon, classes, children}: ButtonProps): JSX.Element {
Убрал кнопку как компонент

2022-02-17 16:46 UTC, BalanarUnity1337 commented on project/src/components/button/button.tsx
> +    <button className={innerClassName} type="button">
+

2022-02-17 16:46 UTC, BalanarUnity1337 commented on project/src/components/film-card-description/film-card-description.tsx
> +        <Button icon={isFavorite ? IconInList() : IconAdd()} classes={['btn--list', 'film-card__button']}>
Поправил

2022-02-17 16:47 UTC, BalanarUnity1337 commented on project/src/components/catalog-genres-item/catalog-genres-item.tsx
> +  const activeClassName: string = active ? 'catalog__genres-item--active' : '';
Переделал `mergeClasses` для поддержки строки и объекта

2022-02-17 16:47 UTC, BalanarUnity1337 commented on project/src/components/my-list/my-list.tsx
> +      <Header classes={['user-page__head']}>
Поправил

2022-02-17 16:49 UTC, BalanarUnity1337 commented on project/src/components/player/player.tsx
> +          <button className="player__play" type="button">
Компонент `Button` убрал. Хотелось, чтобы кнопка имела общий класс, но `btn` присутствует не на всех кнопках в макетах, поэтому убрал.

2022-02-17 16:49 UTC, BalanarUnity1337 commented on project/src/components/film-card/film-card.tsx
> +    <article className="small-film-card  catalog__films-card">
Поправил

2022-02-17 16:49 UTC, BalanarUnity1337 commented on project/src/components/icons/icon-add/icon-add.tsx
> +function IconAdd(): JSX.Element {
Решил оставить, но иконки переместил в общую директорию

2022-02-17 16:50 UTC, BalanarUnity1337 commented on project/src/components/sign-in/sign-in.tsx
> +      <Header classes={['user-page__head']}>
Поправил

2022-02-17 16:50 UTC, BalanarUnity1337 commented on project/src/components/sign-in-field/sign-in-field.tsx
> +      <label className="sign-in__label  visually-hidden" htmlFor={id}>{label}</label>
Поправил

2022-02-17 21:12 UTC, dianatsevan approved these changes

2022-02-17 21:12 UTC, dianatsevan commented on project/src/shared/lib/mergeClasses.ts
> +  classes?: Record<string, boolean | undefined> | string,
Почему `undefined`?

2022-02-17 21:12 UTC, dianatsevan commented on project/src/shared/lib/mergeClasses.ts
> +  let result = staticClass;
Есть идея записать в переменную `result` не просто строку `staticClass`, а `[staticClass]`. В таком случае мы бы просто пушили в массив, а в конце из функции возвращали `result.join(' ')`. Думаю, так код был бы более понятен, чем конкатенация строк

2022-02-17 21:12 UTC, dianatsevan commented on project/src/shared/lib/mergeClasses.ts
> +const mergeClasses = (
Почему решил перенести файл в новую папку?

2022-02-17 21:14 UTC, dianatsevan commented
Пр апрувд. Оставила несколько опциональных комментариев. Отличная работа!

2022-02-17 21:14 UTC, merged